### ISSUE TITLE
Depends on go1.15 that is not supported by brew anymore

### ISSUE THREAD

**Issue by quinze** [barnardb/cookies#3]
brew install barnardb/cookies/cookies
Error: go@1.15 has been disabled because it is not supported upstream!

**Comment by shahata** [comment]
+1

**Comment by frizadiga** [comment]
+1

**Comment by Huge** [comment]
+1

It won't install even when explicitly asked with `brew install go@1.15`.

Maybe we [post a bounty](bountysource.com) or something?..

**Comment by barnardb** [comment]
My apologies for the issue with the pinned dependency.

The Homebrew formula now uses the latest go version. You should be good to go with:
```sh
brew up && brew install barnardb/cookies/cookies
```
